import type { MealPlan } from "@/types/domain";

export const mealPlans: MealPlan[] = [
  {
    id: "weekday-home-style",
    name: "Weekday Home-Style Dabba",
    providerName: "Tiffin Theory",
    mealStyle: "Rotating vegetarian home-style lunch",
    dietaryTags: ["vegetarian"],
    mealsPerDelivery: 1,
    deliveryDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    cadenceLabel: "Every weekday",
    durationWeeks: 4,
    pricePerDelivery: 179,
    planPrice: 3580,
    firstDeliveryWindowId: "lunch-tomorrow",
    availableDestinationIds: ["bkc-office", "andheri-studio"],
    isAvailable: true,
    promotion: "Save ₹200 across four weeks",
  },
  {
    id: "balanced-office-plan",
    name: "Balanced Office Tiffin",
    providerName: "Greenline Kitchen",
    mealStyle: "Vegetarian grain bowls with seasonal sides",
    dietaryTags: ["vegetarian", "vegan"],
    mealsPerDelivery: 1,
    deliveryDays: ["Mon", "Wed", "Fri"],
    cadenceLabel: "Three days a week",
    durationWeeks: 4,
    pricePerDelivery: 219,
    planPrice: 2628,
    firstDeliveryWindowId: "lunch-tomorrow",
    availableDestinationIds: ["bkc-office", "powai-home"],
    isAvailable: true,
    promotion: null,
  },
  {
    id: "family-dinner-dabba",
    name: "Family Dinner Dabba",
    providerName: "Dosa District",
    mealStyle: "South Indian dinner with rotating sides",
    dietaryTags: ["vegetarian"],
    mealsPerDelivery: 2,
    deliveryDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    cadenceLabel: "Every weekday",
    durationWeeks: 2,
    pricePerDelivery: 299,
    planPrice: 2990,
    firstDeliveryWindowId: "dinner-today",
    availableDestinationIds: ["powai-home"],
    isAvailable: true,
    promotion: null,
  },
];

export const mealPlanById = Object.fromEntries(
  mealPlans.map((plan) => [plan.id, plan]),
) as Record<string, MealPlan>;
