import type {
  CustomizationGroup,
  MenuCategory,
  MenuItem,
} from "@/types/domain";

export const menuCategories: MenuCategory[] = [
  { id: "tiffin-breakfast", restaurantId: "tiffin-theory", name: "Breakfast", description: "Fast, warm starts", sortOrder: 1 },
  { id: "tiffin-beverages", restaurantId: "tiffin-theory", name: "Beverages", description: "Filter coffee and chai", sortOrder: 2 },
  { id: "dosa-signatures", restaurantId: "dosa-district", name: "Signatures", description: "Crisp dosa plates", sortOrder: 1 },
  { id: "dosa-beverages", restaurantId: "dosa-district", name: "Beverages", description: "South Indian classics", sortOrder: 2 },
  { id: "bowl-favourites", restaurantId: "bombay-bowl", name: "Bowls", description: "Balanced bowls for the ride", sortOrder: 1 },
  { id: "bowl-beverages", restaurantId: "bombay-bowl", name: "Drinks", description: "Fresh and cooling", sortOrder: 2 },
  { id: "chai-wraps", restaurantId: "monsoon-chai", name: "Wraps & Bites", description: "Easy to carry", sortOrder: 1 },
  { id: "chai-beverages", restaurantId: "monsoon-chai", name: "Chai Bar", description: "Brewed for the commute", sortOrder: 2 },
  { id: "biryani-mains", restaurantId: "biryani-chapter", name: "Biryani", description: "Layered and fragrant", sortOrder: 1 },
  { id: "biryani-sides", restaurantId: "biryani-chapter", name: "Sides", description: "Complete the box", sortOrder: 2 },
  { id: "greenline-bowls", restaurantId: "greenline-kitchen", name: "Bowls", description: "Fresh, light and bright", sortOrder: 1 },
  { id: "greenline-drinks", restaurantId: "greenline-kitchen", name: "Drinks", description: "Cold-pressed and fresh", sortOrder: 2 },
];

export const customizationGroups: CustomizationGroup[] = [
  {
    id: "dosa-size",
    name: "Choose a size",
    selectionMode: "single",
    required: true,
    options: [
      { id: "regular", label: "Regular", priceDelta: 0, isDefault: true },
      { id: "ghee-roast", label: "Ghee roast", priceDelta: 35, isDefault: false },
    ],
  },
  {
    id: "dosa-spice",
    name: "Spice preference",
    selectionMode: "single",
    required: true,
    options: [
      { id: "mild", label: "Mild", priceDelta: 0, isDefault: true },
      { id: "classic", label: "Classic", priceDelta: 0, isDefault: false },
      { id: "fiery", label: "Fiery", priceDelta: 0, isDefault: false },
    ],
  },
  {
    id: "bowl-addons",
    name: "Add-ons",
    selectionMode: "multiple",
    required: false,
    options: [
      { id: "paneer", label: "Tandoori paneer", priceDelta: 55, isDefault: false },
      { id: "avocado", label: "Avocado", priceDelta: 70, isDefault: false },
      { id: "extra-dressing", label: "Extra dressing", priceDelta: 20, isDefault: false },
    ],
  },
  {
    id: "biryani-spice",
    name: "Heat level",
    selectionMode: "single",
    required: true,
    options: [
      { id: "gentle", label: "Gentle", priceDelta: 0, isDefault: true },
      { id: "classic", label: "Classic", priceDelta: 0, isDefault: false },
      { id: "hot", label: "Hot", priceDelta: 0, isDefault: false },
    ],
  },
];

export const menuItems: MenuItem[] = [
  {
    id: "masala-poha",
    restaurantId: "tiffin-theory",
    categoryId: "tiffin-breakfast",
    name: "Indori Masala Poha",
    description: "Peanuts, sev, coriander, and a squeeze of lime.",
    imageUrl: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=700&q=85",
    basePrice: 99,
    dietaryTags: ["vegetarian", "vegan"],
    isBestseller: true,
    preparationMinutes: 8,
    customizationGroupIds: [],
    isAvailable: true,
  },
  {
    id: "idli-podi-box",
    restaurantId: "tiffin-theory",
    categoryId: "tiffin-breakfast",
    name: "Idli Podi Box",
    description: "Four soft idlis with podi, chutney, and sambar.",
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=700&q=85",
    basePrice: 129,
    dietaryTags: ["vegetarian", "vegan"],
    isBestseller: false,
    preparationMinutes: 10,
    customizationGroupIds: [],
    isAvailable: true,
  },
  {
    id: "filter-coffee",
    restaurantId: "tiffin-theory",
    categoryId: "tiffin-beverages",
    name: "South Indian Filter Coffee",
    description: "Small-batch decoction with steamed milk.",
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=700&q=85",
    basePrice: 69,
    dietaryTags: ["vegetarian"],
    isBestseller: true,
    preparationMinutes: 5,
    customizationGroupIds: [],
    isAvailable: true,
  },
  {
    id: "masala-dosa",
    restaurantId: "dosa-district",
    categoryId: "dosa-signatures",
    name: "Classic Masala Dosa",
    description: "Potato masala, sambar, and two chutneys.",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=700&q=85",
    basePrice: 149,
    dietaryTags: ["vegetarian"],
    isBestseller: true,
    preparationMinutes: 10,
    customizationGroupIds: ["dosa-size", "dosa-spice"],
    isAvailable: true,
  },
  {
    id: "paneer-bowl",
    restaurantId: "bombay-bowl",
    categoryId: "bowl-favourites",
    name: "Tandoori Paneer Bowl",
    description: "Paneer, brown rice, greens, corn salsa, and mint dressing.",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=85",
    basePrice: 229,
    dietaryTags: ["vegetarian"],
    isBestseller: true,
    preparationMinutes: 14,
    customizationGroupIds: ["bowl-addons"],
    isAvailable: true,
  },
  {
    id: "avocado-chickpea-bowl",
    restaurantId: "bombay-bowl",
    categoryId: "bowl-favourites",
    name: "Avocado Chickpea Bowl",
    description: "Chickpeas, avocado, pickled onions, and toasted seeds.",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=85",
    basePrice: 249,
    dietaryTags: ["vegetarian", "vegan"],
    isBestseller: false,
    preparationMinutes: 13,
    customizationGroupIds: ["bowl-addons"],
    isAvailable: true,
  },
  {
    id: "paneer-kathi-wrap",
    restaurantId: "monsoon-chai",
    categoryId: "chai-wraps",
    name: "Smoky Paneer Kathi Wrap",
    description: "Roomali roti, smoky paneer, onion, and green chutney.",
    imageUrl: "https://images.unsplash.com/photo-1626776876729-bab4369f2a5a?auto=format&fit=crop&w=700&q=85",
    basePrice: 139,
    dietaryTags: ["vegetarian"],
    isBestseller: true,
    preparationMinutes: 8,
    customizationGroupIds: [],
    isAvailable: true,
  },
  {
    id: "chicken-biryani",
    restaurantId: "biryani-chapter",
    categoryId: "biryani-mains",
    name: "Hyderabadi Chicken Biryani",
    description: "Long-grain rice, saffron, fried onions, and raita.",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03246963d51a?auto=format&fit=crop&w=700&q=85",
    basePrice: 249,
    dietaryTags: ["contains-meat"],
    isBestseller: true,
    preparationMinutes: 19,
    customizationGroupIds: ["biryani-spice"],
    isAvailable: true,
  },
  {
    id: "veg-biryani",
    restaurantId: "biryani-chapter",
    categoryId: "biryani-mains",
    name: "Subz Dum Biryani",
    description: "Seasonal vegetables, basmati rice, and cooling raita.",
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=700&q=85",
    basePrice: 219,
    dietaryTags: ["vegetarian"],
    isBestseller: false,
    preparationMinutes: 17,
    customizationGroupIds: ["biryani-spice"],
    isAvailable: true,
  },
  {
    id: "greenline-salad",
    restaurantId: "greenline-kitchen",
    categoryId: "greenline-bowls",
    name: "Citrus Crunch Bowl",
    description: "Greens, roasted sweet potato, citrus, and seeds.",
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=85",
    basePrice: 255,
    dietaryTags: ["vegetarian", "vegan"],
    isBestseller: true,
    preparationMinutes: 18,
    customizationGroupIds: [],
    isAvailable: false,
  },
];

export const categoryById = Object.fromEntries(
  menuCategories.map((category) => [category.id, category]),
) as Record<string, MenuCategory>;

export const customizationGroupById = Object.fromEntries(
  customizationGroups.map((group) => [group.id, group]),
) as Record<string, CustomizationGroup>;
