import type { PickupPoint, Restaurant } from "@/types/domain";

export const pickupPoints: PickupPoint[] = [
  {
    id: "powai-start",
    name: "Powai Start Hub",
    routeProgressPercentage: 8,
    distanceFromRouteMeters: 90,
    accessNote: "Inside the Hiranandani walking lane",
    restaurantIds: ["tiffin-theory", "dosa-district"],
  },
  {
    id: "ghatkopar-metro",
    name: "Ghatkopar Metro Exit 2",
    routeProgressPercentage: 29,
    distanceFromRouteMeters: 140,
    accessNote: "Exit 2, beside the metro concourse",
    restaurantIds: ["bombay-bowl", "monsoon-chai"],
  },
  {
    id: "bkc-hub",
    name: "BKC Food Lane",
    routeProgressPercentage: 45,
    distanceFromRouteMeters: 180,
    accessNote: "Ground floor, opposite the shuttle bay",
    restaurantIds: ["biryani-chapter"],
  },
  {
    id: "dadar-station",
    name: "Dadar Station West",
    routeProgressPercentage: 67,
    distanceFromRouteMeters: 120,
    accessNote: "West footbridge, near the taxi queue",
    restaurantIds: ["greenline-kitchen"],
  },
  {
    id: "kandivali-terminal",
    name: "Kandivali West Pickup Bay",
    routeProgressPercentage: 88,
    distanceFromRouteMeters: 210,
    accessNote: "Pickup bay beside the station entrance",
    restaurantIds: ["greenline-kitchen"],
  },
];

export const restaurants: Restaurant[] = [
  {
    id: "tiffin-theory",
    name: "Tiffin Theory",
    cuisine: "South Indian breakfast",
    imageUrl:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85",
    rating: 4.7,
    ratingsCount: 1840,
    averagePrice: 160,
    preparationMinutes: 11,
    dietaryTags: ["vegetarian"],
    isOpen: true,
    promotion: "Breakfast combo at ₹129",
    popularityScore: 0.88,
    frequentRouteScore: 0.92,
    routeProgressPercentage: 18,
    detourMinutes: 2,
    estimatedUserArrivalMinutes: 22,
    pickupPointId: "powai-start",
    menuCategoryIds: ["tiffin-breakfast", "tiffin-beverages"],
  },
  {
    id: "dosa-district",
    name: "Dosa District",
    cuisine: "Crisp dosas and filter coffee",
    imageUrl:
      "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=900&q=85",
    rating: 4.5,
    ratingsCount: 1210,
    averagePrice: 185,
    preparationMinutes: 10,
    dietaryTags: ["vegetarian"],
    isOpen: true,
    promotion: null,
    popularityScore: 0.78,
    frequentRouteScore: 0.76,
    routeProgressPercentage: 24,
    detourMinutes: 1,
    estimatedUserArrivalMinutes: 14,
    pickupPointId: "powai-start",
    menuCategoryIds: ["dosa-signatures", "dosa-beverages"],
  },
  {
    id: "bombay-bowl",
    name: "Bombay Bowl Co.",
    cuisine: "Fresh Indian bowls",
    imageUrl:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85",
    rating: 4.6,
    ratingsCount: 980,
    averagePrice: 229,
    preparationMinutes: 16,
    dietaryTags: ["vegetarian", "vegan"],
    isOpen: true,
    promotion: "Save ₹40 on bowls",
    popularityScore: 0.81,
    frequentRouteScore: 0.84,
    routeProgressPercentage: 42,
    detourMinutes: 2,
    estimatedUserArrivalMinutes: 14,
    pickupPointId: "ghatkopar-metro",
    menuCategoryIds: ["bowl-favourites", "bowl-beverages"],
  },
  {
    id: "monsoon-chai",
    name: "Monsoon Chai & Co.",
    cuisine: "Chai, wraps, and quick bites",
    imageUrl:
      "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=900&q=85",
    rating: 4.3,
    ratingsCount: 760,
    averagePrice: 145,
    preparationMinutes: 8,
    dietaryTags: ["vegetarian", "contains-egg"],
    isOpen: true,
    promotion: "Chai + wrap from ₹99",
    popularityScore: 0.74,
    frequentRouteScore: 0.86,
    routeProgressPercentage: 56,
    detourMinutes: 4,
    estimatedUserArrivalMinutes: 17,
    pickupPointId: "ghatkopar-metro",
    menuCategoryIds: ["chai-wraps", "chai-beverages"],
  },
  {
    id: "biryani-chapter",
    name: "Biryani Chapter",
    cuisine: "Hyderabadi biryani",
    imageUrl:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=85",
    rating: 4.5,
    ratingsCount: 1460,
    averagePrice: 249,
    preparationMinutes: 19,
    dietaryTags: ["contains-meat"],
    isOpen: true,
    promotion: "Free raita on pre-orders",
    popularityScore: 0.91,
    frequentRouteScore: 0.71,
    routeProgressPercentage: 48,
    detourMinutes: 3,
    estimatedUserArrivalMinutes: 18,
    pickupPointId: "bkc-hub",
    menuCategoryIds: ["biryani-mains", "biryani-sides"],
  },
  {
    id: "greenline-kitchen",
    name: "Greenline Kitchen",
    cuisine: "Healthy bowls and wraps",
    imageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85",
    rating: 4.1,
    ratingsCount: 540,
    averagePrice: 275,
    preparationMinutes: 22,
    dietaryTags: ["vegetarian", "vegan"],
    isOpen: false,
    promotion: "Back at 11:30 AM",
    popularityScore: 0.63,
    frequentRouteScore: 0.68,
    routeProgressPercentage: 73,
    detourMinutes: 1,
    estimatedUserArrivalMinutes: 15,
    pickupPointId: "dadar-station",
    menuCategoryIds: ["greenline-bowls", "greenline-drinks"],
  },
];

export const restaurantById = Object.fromEntries(
  restaurants.map((restaurant) => [restaurant.id, restaurant]),
) as Record<string, Restaurant>;

export const pickupPointById = Object.fromEntries(
  pickupPoints.map((pickupPoint) => [pickupPoint.id, pickupPoint]),
) as Record<string, PickupPoint>;
